### PR TITLE
Update iOS SDK to 1.6.1 and Android SDK to 1.5.4

### PR DESCRIPTION
**Pull request by kolotum**
### Requirements

- [ ] I have added test coverage for new or changed functionality
- [x] I have followed the repository's [pull request submission guidelines](../blob/master/CONTRIBUTING.md#submitting-pull-requests)
- [x] I have validated my changes against all supported platform versions

### Describe the solution you've provided

This PR updates Survicate iOS SDK to 1.6.1 and Android SDK to 1.5.4.

Also some Android related config is updated as well so the example app could be run locally:
- Kotlin version: 1.4.32
- Android Gradle plugin: 4.2.2
- gradle-wrapper: 6.7.1

### CODE REVIEW

**Review by andre-paraense — CHANGES_REQUESTED** [review]
When running the example app, the iOS version works fine for all features. However, the Android version fails on some of them. For instance, when the "Invoke event SURVEY" button is pressed, we get the following exception:

`E/MethodChannel#survicate_flutter_sdk(32047): Failed to handle method call
E/MethodChannel#survicate_flutter_sdk(32047): com.squareup.moshi.JsonDataException: java.lang.IllegalArgumentException: Unknown color at $.surveys[0].theme.overlay
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:101)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:243)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:203)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:243)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:203)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:84)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.survicate.surveys.infrastructure.serialization.MoshiSurvicateSerializer.deserializeWorkspace(MoshiSurvicateSerializer.java:88)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.survicate.surveys.infrastructure.storage.SerializedSharedPrefsSurvicateStore.loadWorkspace(SerializedSharedPrefsSurvicateStore.java:134)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.survicate.surveys.PersistenceManager.loadWorkspace(PersistenceManager.java:285)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.survicate.surveys.Survicate.resetIfOutdated(Survicate.java:199)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.survicate.surveys.Survicate.invokeEvent(Survicate.java:141)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.oakam.survicate.survicate_flutter_sdk.SurvicateFlutterSdkPlugin.onMethodCall(SurvicateFlutterSdkPlugin.kt:35)
E/MethodChannel#survicate_flutter_sdk(32047): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#survicate_flutter_sdk(32047): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/MethodChannel#survicate_flutter_sdk(32047): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/MethodChannel#survicate_flutter_sdk(32047): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/MethodChannel#survicate_flutter_sdk(32047): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#survicate_flutter_sdk(32047): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#survicate_flutter_sdk(32047): 	at android.os.Looper.loop(Looper.java:223)
E/MethodChannel#survicate_flutter_sdk(32047): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#survicate_flutter_sdk(32047): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/MethodChannel#survicate_flutter_sdk(32047): Caused by: java.lang.IllegalArgumentException: Unknown color
E/MethodChannel#survicate_flutter_sdk(32047): 	at android.graphics.Color.parseColor(Color.java:1391)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.survicate.surveys.infrastructure.serialization.MoshiColorAdapter.fromJson(MoshiColorAdapter.java:17)
E/MethodChannel#survicate_flutter_sdk(32047): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.AdapterMethodsFactory$AdapterMethod.invoke(AdapterMethodsFactory.java:383)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.AdapterMethodsFactory$5.fromJson(AdapterMethodsFactory.java:296)
E/MethodChannel#survicate_flutter_sdk(32047): 	at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:97)
E/MethodChannel#survicate_flutter_sdk(32047): 	... 29 more
E/flutter (32047): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, java.lang.IllegalArgumentException: Unknown color at $.surveys[0].theme.overlay, null, com.squareup.moshi.JsonDataException: java.lang.IllegalArgumentException: Unknown color at $.surveys[0].theme.overlay
E/flutter (32047): 	at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:101)
E/flutter (32047): 	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:243)
E/flutter (32047): 	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:203)
E/flutter (32047): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E/flutter (32047): 	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:243)
E/flutter (32047): 	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:203)
E/flutter (32047): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E/flutter (32047): 	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
E/flutter (32047): 	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
E/flutter (32047): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E/flutter (32047): 	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:84)
E/flutter (32047): 	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
E/flutter (32047): 	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
E/flutter (32047): 	at com.survicate.surveys.infrastructure.serialization.MoshiSurvicateSerializer.deserializeWorkspace(MoshiSurvicateSerializer.java:88)
E/flutter (32047): 	at com.survicate.surveys.infrastructure.storage.SerializedSharedPrefsSurvicateStore.loadWorkspace(SerializedSharedPrefsSurvicateStore.java:134)
E/flutter (32047): 	at com.survicate.surveys.PersistenceManager.loadWorkspace(PersistenceManager.java:285)
E/flutter (32047): 	at com.survicate.surveys.Survicate.resetIfOutdated(Survicate.java:199)
E/flutter (32047): 	at com.survicate.surveys.Survicate.invokeEvent(Survicate.java:141)
E/flutter (32047): 	at com.oakam.survicate.survicate_flutter_sdk.SurvicateFlutterSdkPlugin.onMethodCall(SurvicateFlutterSdkPlugin.kt:35)
E/flutter (32047): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (32047): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/flutter (32047): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/flutter (32047): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/flutter (32047): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (32047): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (32047): 	at android.os.Looper.loop(Looper.java:223)
E/flutter (32047): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (32047): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (32047): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (32047): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (32047): Caused by: java.lang.IllegalArgumentException: Unknown color
E/flutter (32047): 	at android.graphics.Color.parseColor(Color.java:1391)
E/flutter (32047): 	at com.survicate.surveys.infrastructure.serialization.MoshiColorAdapter.fromJson(MoshiColorAdapter.java:17)
E/flutter (32047): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (32047): 	at com.squareup.moshi.AdapterMethodsFactory$AdapterMethod.invoke(AdapterMethodsFactory.java:383)
E/flutter (32047): 	at com.squareup.moshi.AdapterMethodsFactory$5.fromJson(AdapterMethodsFactory.java:296)
E/flutter (32047): 	at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:97)
E/flutter (32047): 	... 29 more
E/flutter (32047): )
E/flutter (32047): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (32047): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (32047): <asynchronous suspension>
E/flutter (32047): #2      SurvicateFlutterSdk.invokeEvent (package:survicate_flutter_sdk/survicate_flutter_sdk.dart:178:12)
E/flutter (32047): <asynchronous suspension>
E/flutter (32047): 
`

**Comment by kolotum** [comment]
> When running the example app, the iOS version works fine for all features. However, the Android version fails on some of them. For instance, when the "Invoke event SURVEY" button is pressed, we get the following exception:
> 
> `E/MethodChannel#survicate_flutter_sdk(32047): Failed to handle method call`

I could not reproduce these exceptions so far. It looks like the Survicate SDK can not deserialize local data.

I am not sure if this is related to data generated with versions before survicate-flutter-sdk 2.1.1 or your workspace has a different configuration.

Do you see these exceptions on fresh app installs as well, e.g. different Android Emulator?

**Comment by andre-paraense** [comment]
> > When running the example app, the iOS version works fine for all features. However, the Android version fails on some of them. For instance, when the "Invoke event SURVEY" button is pressed, we get the following exception:
> > `E/MethodChannel#survicate_flutter_sdk(32047): Failed to handle method call`
> 
> I could not reproduce these exceptions so far. It looks like the Survicate SDK can not deserialize local data.
> 
> I am not sure if this is related to data generated with versions before survicate-flutter-sdk 2.1.1 or your workspace has a different configuration.
> 
> Do you see these exceptions on fresh app installs as well, e.g. different Android Emulator?

Yes, I can reproduce the exception even after cleaning my workspace (`$ flutter clean`) and spinning up a brand new emulator.

Have you tested the Android app connected to an actual Survicate account (substituting the workspace key in your AndroidManifest.xml and having actual surveys created and triggered by the `"Invoke event SURVEY"`)?

**Comment by kolotum** [comment]
> Have you tested the Android app connected to an actual Survicate account (substituting the workspace key in your AndroidManifest.xml and having actual surveys created and triggered by the `"Invoke event SURVEY"`)?

Yes, I replaced the workspace key and could see the enabled mobile app survey running the example app on Android without exceptions.

**Comment by andre-paraense** [comment]
> > Have you tested the Android app connected to an actual Survicate account (substituting the workspace key in your AndroidManifest.xml and having actual surveys created and triggered by the `"Invoke event SURVEY"`)?
> 
> Yes, I replaced the workspace key and could see the enabled mobile app survey running the example app on Android without exceptions.

Great, thanks for the confirmation. But have you created a survey that is triggered by an event and then clicked the `Invoke event SURVEY` button on the example app to check that the survey is being triggered and shown? Because that is when the exception is thrown.

**Pull request closed without merging**
